- .github/workflows/build/action.yml
- .github/workflows/cla.yml
- .github/workflows/deploy-release.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/tag-release.yml
- .github/workflows/test.yml
- .github/workflows/yarn/action.yml
- next.config.js
- package.json
- pages/_app.tsx
- scripts/github/prepare_production_deployment.sh
- scripts/github/s3_upload.sh
- yarn.lock
Implements deployments.
Deployment scripts have been copied over from `web-core`, customised to match this repo.
> chore: add deployment scripts

- .github/workflows/ISSUE_TEMPLATE/bug-report.md
- .github/workflows/PULL_REQUEST_TEMPLATE.md
- README.md
Resolves missing deployment and templates.
The production deployment as been added to the readme, as well as templates for PRs and bug reports added.
> chore: update readme + add templates

- src/components/DashboardWidgets/ClaimingWidget.tsx
- src/components/Sep5InfoBox/index.tsx
Design issues
1. The widget outline (in light mode) is now green, as well as the background of the claim date within it.
2. Tooltips were fixed when hovering over the claim dates on the widget/claim page.
Observe the corrections metioned above in the UI
> [EPIC] SEP #5 - Design adjustments

- .github/workflows/cla.yml
- pages/_app.tsx
- src/components/Claim/steps/SuccessfulClaim/index.tsx
- src/components/DashboardWidgets/ClaimingWidget.tsx
- src/hooks/useIsDarkMode.ts
- src/styles/theme.ts
- src/utils/onboard.ts
Only allow dark mode in governance and locking app, ignore user preference.
> Enforce dark mode across the app

- src/components/TockenUnlocking/UnlockStats.tsx
- src/components/TockenUnlocking/styles.module.css
- src/components/TokenAmount/index.tsx
- src/components/TokenAmount/styles.module.css
- src/components/TokenLocking/CurrentStats.tsx
- Unifies token amount components
- uses new component for token locking stats
> Fix: token amount components

- src/components/Claim/index.tsx
- src/components/ClaimCard/index.tsx
- src/components/InfoAlert/index.tsx
- src/components/OverviewLinks/index.tsx
- src/components/SelectedDelegate/index.tsx
Fixes the issues specified here: https://www.notion.so/safe-global/Design-changes-to-governance-claiming-app-22cc205e7c49442198c33b16d8d25ac8
> Fix: correct wording and styles in the governance app

- src/components/TockenUnlocking/index.tsx
- src/components/TockenUnlocking/styles.module.css
> Fix: withdraw button layout

- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/components/TokenLocking/BoostGraph/helper.ts
- Does not create duplicate points in the graph which lead to wrong colors.
> Fix: multiple locks today

- src/components/TokenLocking/MilesReceipt.tsx
- src/components/TokenLocking/styles.module.css
- rephrases success modals to highlight that changes will only be reflected once the tx is fully executed.
- Fixes width of right side of success modal.
> fix: miles receipt wording and width

- src/components/WalletIcon/index.tsx
- src/utils/onboard.ts
- Fixes the wallet icon of the header in the standalone app
> Fix: show wallet icon in header

- src/components/NavTabs/styles.module.css
- src/components/PageLayout/styles.module.css
- src/components/SplashScreen/index.tsx
- src/components/TockenUnlocking/index.tsx
- Makes container a flex with centered children.
- sets max-width for unlock page
> Fix: center page layout and fix width of unlock page

- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- Renders today scatter point in different component to avoid disappearing today labels
> Fix: today tooltip

- src/components/TokenLocking/ActivityRewardsInfo.tsx
- src/components/TokenLocking/Leaderboard.tsx
- src/components/TokenLocking/index.tsx
- src/styles/theme.ts
- Moved T&C link to sidebar
- Removes dates from sidebar
- Removes lottery
> Feat: adjust right sidebar

- src/components/SplashScreen/index.tsx
https://www.notion.so/safe-global/WC-if-the-connection-for-the-EOA-is-not-available-we-should-inform-about-it-better-c2a3b6902317436ab69f016fb1dbc676?pvs=4
> Fix: display error on standalone app when connected wallet is not a safe

- src/hooks/__tests__/useSafeTokenAllocation.test.ts
- src/hooks/useSafeTokenAllocation.ts
- src/utils/lock.ts
voting power is now:
vested tokens + held tokens + tokens in contract
https://www.notion.so/safe-global/Change-voting-power-computation-08023afef09e4676b7a9020d0d7ba7f3?pvs=4
> Feat: include locking contract tokens in voting power calculation

- src/components/MediumPaper/index.tsx
- src/components/MediumPaper/styles.module.css
- src/components/PageLayout/index.tsx
- src/components/TokenLocking/BoostBreakdown.tsx
- src/components/TokenLocking/BoostGraph/ActionNavigation/styles.module.css
- src/components/TokenLocking/MilesReceipt.tsx
- src/components/TokenLocking/styles.module.css
- Standalone app layout when on mobile
- Responsive MilesReceipts
> Fix: responsiveness bugs

- src/components/TokenLocking/index.tsx
Add legal disclaimer as shown.
> Feat: Add legal disclaimer to the bottom of the page

- src/components/TokenLocking/BoostBreakdown.tsx
- src/components/TokenLocking/BoostGraph/BoostGradients.tsx
- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/utils/__tests__/boost.test.ts
- src/utils/boost.ts
- Exchanges boost function
- adjusts unit tests
- changes scale of graph Y-axis
- adjusts scatter plot to use currentBoost on today point and projected boost on last day
- Removes realized and finalized boost (shows only 1 number instead)
> Feat: new boost function

- src/components/TokenLocking/BoostGraph/AxisTopLabel.tsx
- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/components/TokenLocking/BoostGraph/graphConstants.ts
- src/config/constants.ts
- Fixes the labels of the graph
- Moves marker to day 27
- Adjusts width and padding slightly
> Fix: adjust graph axis

- public/manifest.json
- Updates App's `manifest.json`
> Chore: update manifest

- src/components/SplashScreen/index.tsx
- src/components/TokenLocking/ActivityRewardsInfo.tsx
- src/components/TokenLocking/MilesReceipt.tsx
- update copy on sidebar, removing references to miles
- rename logo to reflect content
- add locking/unlocking receipt barcode back in
> Feat: Update copy on the activity rewards sidebar

- pages/_document.tsx
Resolves #56 
- Adds robots meta tag
- Instructs not to index dev & staging
- Instructs to not follow links
https://nextjs.org/learn-pages-router/seo/crawling-and-indexing/metatags
> chore: do not index dev & staging, do not follow links

- src/components/TokenLocking/Leaderboard.tsx
- src/config/constants.ts
- Links addresses in the leaderboard to the blockexplorer
> Feat: link to blockexplorer from leaderboard

- src/components/Activities/index.tsx
- src/components/PageLayout/index.tsx
- src/components/TokenLocking/ActivityRewardsInfo.tsx
- src/components/TokenLocking/BoostBreakdown.tsx
- src/components/TokenLocking/BoostGraph/ActionNavigation/ActionNavigation.tsx
- src/components/TokenLocking/BoostMeter.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
- src/components/TokenLocking/index.tsx
- Adds link to landing page next to page title
- BoostMeter shows how many days the full boost will be available
- small rephrasing
> Fix: last copy changes on locking page

- src/components/SplashScreen/index.tsx
- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- src/components/TokenLocking/BoostBreakdown.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
- src/components/TokenLocking/MilesReceipt.tsx
- Fixes some wordings
- Replaces remaining "miles" with "points"
> fix: copy bugs

- src/components/TokenLocking/MilesReceipt.tsx
> fix: update tweet content

- src/components/Activities/index.tsx
- Removes whitespace between Safe and {Pass}
- Changes twitter link to follow intent
> fix: small adjustments to text and links

- src/components/TokenLocking/index.tsx
Update to most recent legal disclaimer: https://www.notion.so/safe-global/Legal-disclaimer-0bde6eeb92e5488ab20d08ee12fa79f6
> fix: update legal disclaimer

- src/components/Claim/index.tsx
- src/components/TokenLocking/index.tsx
- Fixes walletconnect icon for the connection.
> Release 2.0.2

- babel.config.js
- jest.setup.js
- package.json
- src/components/AccountCenter/index.tsx
- src/components/TokenAmount/index.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
- src/components/WalletIcon/index.tsx
- src/components/WalletInfo/index.tsx
- src/config/constants.ts
- src/hooks/useWallet.ts
- src/utils/onboard.ts
- yarn.lock
It's now possible to connect to injected wallets like Nest.
I've also fixed 0 token amount handling.
> Feat: add injected wallet option

- src/utils/onboard.ts
Until all edge cases are ironed out.
> Fix: temporarily disable injected wallets

- src/components/TokenLocking/BoostBreakdown.tsx
- src/components/TokenLocking/BoostGraph/ArrowDownLabel.tsx
- src/components/TokenLocking/BoostGraph/AxisTopLabel.tsx
- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/components/TokenLocking/BoostGraph/ScatterDot.tsx
- src/components/TokenLocking/BoostGraph/graphConstants.ts
- src/components/TokenLocking/BoostGraph/helper.ts
- src/components/TokenLocking/BoostGraph/theme.ts
- src/components/TokenLocking/LockTokenWidget.tsx
Resolves #173 
- Shows tooltips on hover
- Fixes some margins / paddings
- Increases font size in graph
> fix: graph layout, small layout tweaks

- src/components/TokenLocking/LockTokenWidget.tsx
Merged dev to main and resolves conflict.
> Chore: merge dev to main

- src/components/Points/CampaignTitle.tsx
- src/components/Points/styles.module.css
- Changes height and padding of chips.
> fix: chip style

- src/components/Points/CampaignDisclaimer.tsx
- src/components/Points/CampaignPromo.tsx
- src/components/Points/index.tsx
- Adds expandable Campaign disclaimer below the campaign information
- Adds link to blog article
> feat: campaign disclaimer
