- src/components/Intro/index.tsx
Impossible navigation as a Safe App
If a `wallet` is not present (currently using the App as a Safe App), navigation is now possible.
Open the App as a Safe App and click either "Claim tokens" or "Redelegate". Observe navigation to the relevant route.
Note: ensure that connecting a Safe to the DApp via WC still opens the Safe App in a new window.
> fix: only check wallet if it is present

- README.md
- public/manifest.json
- src/components/Claim/steps/SuccessfulClaim/index.tsx
- src/components/ConnectWallet/index.tsx
- src/components/DashboardWidgets/ClaimingWidget.tsx
- src/components/DashboardWidgets/SnapshotWidget.tsx
- src/components/DashboardWidgets/__tests__/SnapshotWidget.test.ts
- src/components/Delegation/steps/SuccessfulDelegation/index.tsx
- src/components/EducationSeries/steps/Disclaimer/index.tsx
- src/components/EducationSeries/steps/Distribution/index.tsx
- src/components/EducationSeries/steps/SafeDao/index.tsx
- src/components/OverviewLinks/index.tsx
Aligns the Safe{DAO} labelling.
All instances of  "Safe {DAO}" have been renamed to "Safe{DAO}".
Open the App and observe all instances of "Safe{DAO}" have no spaces.
> fix: rename "Safe {DAO}" to "Safe{DAO}"

- .github/workflows/deploy.yml
`set-output` will be deprecated in May this year, so [we need to migrate it](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
If the deployment in this PR works, then all is correct.
> chore: replace deprecated `set-output`

- src/components/DashboardWidgets/ClaimingWidget.tsx
Invalid Safe address in claiming widget link.
The `chainId` from the Safe is used.
1. Exchange the widget link with this deployment.
2. Connect wallet to non-Goerli network.
3. Open Safe with allocation.
4. Click link on claiming widget and observe it open on Goerli.
> fix: use Safe `chainId` for claiming widget

- src/components/Claim/steps/ClaimOverview/index.tsx
- src/components/Claim/steps/SuccessfulClaim/index.tsx
- src/components/CustomDelegate/index.tsx
- src/components/DashboardWidgets/ClaimingWidget.tsx
- src/components/Delegation/steps/SelectDelegate/index.tsx
- src/components/EducationSeries/steps/Disclaimer/index.tsx
- src/components/EducationSeries/steps/Distribution/index.tsx
- src/components/EducationSeries/steps/SafeDao/index.tsx
- src/components/EducationSeries/steps/SafeInfo/index.tsx
- src/components/EducationSeries/steps/SafeToken/index.tsx
- src/components/Intro/index.tsx
- src/components/SelectedDelegate/index.tsx
- src/hooks/__tests__/useEnsResolution.test.ts
- src/hooks/useEnsResolution.ts
- src/hooks/useSafeTokenAllocation.ts
Brand alignment
All of the following instances have been updated according to our [brand map](https://docs.google.com/presentation/d/1c7IHqREWFvKtc5ngV1uZBi9eDp2ocHld0fWLBkTyQPs).
"Safe" (project) -> "Safe" (italicised)
"Safe" (contract) -> "Safe Account"
"Safe" (interface) -> "Safe{Wallet}"
Token(s) / token(s)-> "SAFE" or "Safe Token(s)"
"Safe App" -> "Safe{App}"
Observe the correct mapping in the changed files.
> fix: align brand

- src/components/Claim/index.tsx
- src/components/CustomDelegate/index.tsx
- src/components/Delegation/index.tsx
- src/components/Delegation/steps/SelectDelegate/index.tsx
- src/components/EducationSeries/index.tsx
- src/hooks/useAddress.ts
- src/services/StepperFactory.tsx
`StepperFactory` improvements
Initial state is now provided directly to the `Stepper.Provider` instead of being initialised on each step.
Navigate through the education series, claiming and delegation steppers and observe no change in behaviour.
> refactor: improve `StepperFactory`

- src/config/constants.ts
Updates claiming data URL
`safe-claiming-app-data.gnosis-safe.io` has been exchanged with `safe-claiming-app-data.safe.global` as per [request](https://5afe.slack.com/archives/C04MQSC3R7Y/p1687260130435589).
Open the app with an address that has an allocation and observe it still correctly displaying.
> fix: update claiming app data URL

- src/utils/onboard.ts
- src/utils/wallet.ts
Resolves WC v1 session caching interfering with v2.
The local session of WC v1 is no longer checked when trying to auto-connect to v2.
Create a session with WC v1 and refresh. Observe that WC v2 does not try to auto-connect.
> fix: don't check WC v1 session for v2 reconnection

- src/components/ConnectWallet/index.tsx
Resolves unclear warning.
This removes the "Where's my wallet?" info box.
Open the wallet connection modal and observe no "Why don't I see my wallet?" information in the modal.
> fix: remove "Where's my wallet?" info

- package.json
- yarn.lock
Resolves `key.pairing` error in console ([as in `saw-wallet-web`](https://github.com/safe-global/safe-wallet-web/issues/2137))
`@web3-onboard/core` has been updated, which includes the latest versions of all WC packages and [the fix](https://github.com/WalletConnect/walletconnect-monorepo/pull/2684) for the reported issue.
Connect to the app with a Safe via WC and observe no errors in either console.
> fix: upgrade `@web3-onboard/core`

- src/components/Claim/steps/ClaimOverview/index.tsx
- src/components/DashboardWidgets/ClaimingWidget.tsx
- src/components/Intro/index.tsx
- src/components/Sep5DeadlineChip/index.tsx
- src/components/Sep5InfoBox/index.tsx
- src/config/constants.ts
- src/hooks/useAllocations.ts
- src/hooks/useMockSep5.ts
- src/hooks/useTaggedAllocations.ts
- src/utils/__tests__/airdrop.test.ts
- src/utils/__tests__/claim.test.ts
- src/utils/airdrop.ts
- src/utils/claim.ts
- src/utils/vesting.ts
Resolves SEP #5 contract interaction
This integrates with a test airdrop contract `0xB1E81Fe4442FA5A0eE38feB7146E547937C6E737`, allocating `69` tokens to `0x5f310dc66F4ecDE9a1769f1B7D75224dA592201e`. All claims are batched with the test contract first to ensure redemptions for SEP #5.
The [above allocation is pushed to the current data locally](https://github.com/safe-global/safe-dao-governance-app/blob/2cb2b3f64e01f7d07ce623c74513a543fb963370/src/hooks/useAllocations.ts#L21-L32) if the Safe is being used with the app. It replaces all previously static mock data in the interface.
1. Open the `0x5f310dc66F4ecDE9a1769f1B7D75224dA592201e` Safe in two windows.
2. Add this PR deployment as a custom Safe App in one.
3. Add the dev deployment (`https://safe-dao-governance.dev.5afe.dev`) as a …
> [EPIC] SEP #5 - Contract interaction

- src/hooks/useAllocations.ts
Removes local mocks
As the "final" claiming data [has been verified locally](https://github.com/safe-global/safe-dao-governance-app/pull/41#issuecomment-1628694240), this removes the reliance on local mock data.
This instead fetches the deployed claiming app data.
Note: the claiming data [has since been updated](https://github.com/safe-global/claiming-app-data/commit/50b251bf8c49b9937fc5d268e44548f66240e06f) to accomodate for a redemption deadline (18.07).
Open a Safe that is part of the test data claim from the test airdrop successfully.
> [EPIC] SEP #5 - Live claiming data test

- src/components/Claim/steps/ClaimOverview/index.tsx
- src/config/constants.ts
Resolves #45
The spelling mistake of "treasury" on the claim overview has been fixed, as well as the timezone to "UTC".
Open the claim overview screen and observe the above fixes.
> fix: timezone + spelling mistake

- src/hooks/__tests__/useSafeTokenAllocation.test.ts
- src/hooks/useSafeTokenAllocation.ts
- src/utils/airdrop.ts
Copies logic from `safe-wallet-web` for redemption memoization, SEP5 qualification and balance calculation.
This copies over the [memoization logic for the redemption date](https://github.com/safe-global/safe-wallet-web/pull/2411), as well as the [deadline check improvement for SEP5 claiming ability](https://github.com/safe-global/safe-wallet-web/pull/2472#discussion_r1309928840) and [balance crash fix](https://github.com/safe-global/safe-wallet-web/pull/2476).
Safes that qualify for SEP5 should function as before.
> fix: memoize redemption, future-proof SEP5 check, prevent balance crash

- .github/workflows/tag-release.yml
Just creating a PR instead of trying to report this privately since the only way to exploit this would be to submit a PR, have it approved, and edit the PR description with an injection payload that no one notices before clicking merge.
**Reference:**
* https://www.praetorian.com/blog/pwn-request-hacking-microsoft-github-repositories-and-more/
> Fix unsafe expression usage

- package.json
- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/hooks/useLockHistory.ts
- yarn.lock
During animations certain parts of the graph flickered due to bugs in the graph library.
It fixes the following aspects
- The today scatter point was always flickering
- The on-load animation was playing unreliably
Changes:
- Removes `animate` prop from certain graph components which do not require animation
- updates to latest victory version, which reworked the VictoryAnimation component (https://github.com/FormidableLabs/victory/pull/2788)
> Fix: reduce graph flickering

- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- src/components/TockenUnlocking/WinthdrawStats.tsx
- src/components/TockenUnlocking/index.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
Errors around transaction execution were not caught.
To test:
- Create a lock / unlock or withdraw transaction
- Abort the signing
- Observe there is no more uncaught error
> Fix: error handling for locking / unlocking and withdrawal

- src/hooks/useSafeTokenBalance.ts
- The query cached a 0 if the address was undefined on the first load until the window got focused again
- Only gives a Query key for the balance query once the address is available
> Fix: initial token amount is zero

- pages/connect.tsx
- src/components/BackgroundCircles/styles.module.css
- src/components/ConnectWallet/index.tsx
- src/components/PageLayout/index.tsx
- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- src/components/TockenUnlocking/index.tsx
- src/components/TokenLocking/ActionNavigation.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
- src/components/WalletIcon/index.tsx
- src/config/constants.ts
- src/config/routes.ts
- src/hooks/useIsSafeApp.ts
- src/hooks/useSafeTokenBalance.ts
- src/hooks/useTxSender.ts
- src/hooks/useWallet.ts
- src/utils/lock.ts
- src/utils/onboard.ts
- src/utils/wallet.ts
- removes all wallets but wallet connect
- Shows connect wallet page if no wallet is connected
- offer locking, unlocking and withdrawal for wallet connect
> Feat: locking, unlocking and withdrawal with walletconnect

- src/components/TokenLocking/ActivityRewardsInfo.tsx
- src/components/TokenLocking/Leaderboard.tsx
- src/components/TokenLocking/index.tsx
Solves: https://www.notion.so/safe-global/Replace-mock-ranking-with-real-rank-ac5377da44994933926be574497e021f?pvs=4
- Display the users rank instead of a placeholder.
- Show nothing if the user does not have a rank yet.
- Also, rename the component from PlaceholderTopRight -> ActivityRewardsInfo
> Feat: Use dynamic value for users rank in activity rewards info banner

- src/components/BoostCounter/index.tsx
Fixes [Notion](https://www.notion.so/safe-global/5300d6ffcb2043cc9e7fcd10bf14dff5?v=97acdfbecf184482a82449013cc519e9&p=e4b0580199c340b5b7be9f12d2e7f3ec&pm=s)
Choose a lock amount so that the graph shows a 1,99x or 2,99x etc. value and observe the same number is visible to the right
> fix: Use Math.floor instead of Math.round for the boost UI

- src/components/TokenLocking/ActivityRewardsInfo.tsx
- src/components/TokenLocking/index.tsx
- Makes the right side stretch to 100% height
> Fix: align heights of right and left activity components

- src/hooks/useLeaderboard.ts
- src/hooks/useLockHistory.ts
- src/hooks/useSafeTokenBalance.ts
Currently the history, leaderboard position and the token balance are only polled when the window gets focused.
This PR adds a refreshInterval to those endpoints.
> Feat: poll lock history and token balance

- src/components/Claim/index.tsx
- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
> fix: Only allow number inputs for claiming, locking, and unlocking fields

- src/utils/__tests__/lock.test.ts
- src/utils/lock.ts
- sorts lock history ascending before creating the relative history from it
- adds unit test to verify this
> Fix: sort history by date

- src/components/EducationSeries/index.tsx
- src/components/StepHeader/index.tsx
- Navigation on close in StepHeader of governance part of app leads to governance page
- Navigation after finishing the educational series leads back to governance app
> Fix: back navigation for governance app screens

- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
- allow typing "," and "." as decimal separator in input fields
- remove decimals from miles receipt (decimals of Safe tokens are irrelevant for the boost)
> Fix: better handling of decimals in input and miles receipt

- src/hooks/useLockHistory.ts
- the default limit is 20
- We based our page calculation on the limit being 100 though
- explicitly sets limit to 100
> fix: set limit explicitly to 100

- src/components/BoostCounter/index.tsx
- Instead of rounding the number we just slice it in BoostCounter to avoid rounding issues caused by incorrect floating point math.
> Fix: rounding in BoostCounter

- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- Returns early in setMaxAmount for unlock if no tokens have been locked before
> fix: ignore max button without any locked tokens

- src/components/AccountCenter/index.tsx
https://www.notion.so/safe-global/Issue-Disconnect-wallet-state-in-the-stand-alone-app-is-not-implemented-00294fb635f24cdb9f53fbb3612a923a?pvs=4
> Fix: redirect to splash screen after disconnecting in the header on the standalone app

- src/components/SplashScreen/index.tsx
On the standalone app, after connecting a wallet on the splash screen, go straight to the app instead of requiring an extra click.
> Fix: Skip continue step on splash screen after connecting a wallet

- src/hooks/useIsSafeApp.ts
The splash screen was continuously redirecting back and forth from the splash screen to the main app. 
Only set the isSafeApp variable once to avoid re-renders
> Fix: infinite re-render on splash screen for standalone app

- src/components/SplashScreen/index.tsx
Automatic redirect from the splash screen was still happening even when there was an error (connected wallet is not a safe)
https://www.notion.so/safe-global/WC-if-the-connection-for-the-EOA-is-not-available-we-should-inform-about-it-better-c2a3b6902317436ab69f016fb1dbc676?pvs=4
Only redirect if the connection is successful.
> Fix: do not redirect from splash screen when there is an error with the connection

- pages/_app.tsx
- src/styles/theme.ts
- The governance widgets are now rendered in light or dark mode depending on the theme query parameter
- If no parameter is present we always use dark mode.
> Fix: widgets in light mode

- src/components/GovernanceAndClaiming/index.tsx
- src/components/GovernanceAndClaiming/styles.module.css
- src/components/TokenLocking/BoostGraph/ActionNavigation/styles.module.css
- src/components/TokenLocking/Leaderboard.tsx
- src/components/TokenLocking/index.tsx
- src/components/TokenLocking/styles.module.css
Fixes: https://www.notion.so/safe-global/Web-boards-44788b2920624e88a7d15da4754bfd10?p=ba8b018af5b64eb9b3bba327aa31acc5&pm=s
- center `Remove SAFE from locking ` text vertically.
After changes:
- fix overlap of subtitle text in leaderboard:
- Add margin to titles on small screens:
> Fix: Responsiveness bugs in leaderboard,  locking widget, and page titles

- src/components/EnsureWalletConnection/index.tsx
- src/components/Redirect/index.tsx
- src/components/SplashScreen/index.tsx
- src/config/constants.ts
- src/utils/safe-apps.ts
- Add optional `query` object to `Redirect` component props
- If set it sets the query parameters when redirecting
- Set initially opened page as query param when redirecting to splash screen
- If the query param requests the governance app we forward there instead of to the activity app
> Fix: open governance tab when clicking the widget

- src/components/TokenLocking/Leaderboard.tsx
- src/hooks/useLeaderboard.ts
Fixes: https://www.notion.so/safe-global/Web-boards-44788b2920624e88a7d15da4754bfd10?p=639a6aed23544c7c8e961d31c07adfec&pm=s
- Only show own highlighted entry at the top if user is not in top 10
> Fix: Don't show duplicate highlighted entry when user is in top 10 of leaderboard

- src/utils/__tests__/boost.test.ts
- src/utils/boost.ts
https://www.notion.so/safe-global/5300d6ffcb2043cc9e7fcd10bf14dff5?v=97acdfbecf184482a82449013cc519e9&p=ff6f078ceeb149508a95289f2dd1ba6b&pm=s
- Handles NaN correctly in TokenBoost function and boost function
> Fix: non number inputs

- src/components/TokenLocking/BoostBreakdown.tsx
- src/components/TokenLocking/BoostGraph/AxisTopLabel.tsx
- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/components/TokenLocking/BoostGraph/ScatterDot.tsx
- src/components/TokenLocking/BoostGraph/helper.ts
- Adjusts labels slightly
- Removes always visible tooltip for today
- uses projected boost for today's marker
- Moves current boost to the boost breakdown
> Fix: small graph adjustments

- src/components/TokenLocking/Leaderboard.tsx
- Adds placeholder text for empty leaderboard
> Fix: empty leaderboard

- src/components/TockenUnlocking/UnlockTokenWidget.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
Lock button is too high in relation to the token input. It is too low when there is an input error.
Center button with the input in both error and non error states
> fix: lock token button alignment

- src/components/Activities/index.tsx
Make the link  `Follow us on X` instead of just `X`
> Fix: Make follow on X link easier to click

- src/components/Claim/index.tsx
Reserve space for the error message so the page below doesn't jump down when the error appears
> Fix: Stop page from jumping from input error message on claim page

- package.json
- src/utils/onboard.ts
- When wallet connect establishes a connection it could not find the app's icon and showed a placeholder
> fix: app icon url for wallet connect

- src/components/TokenLocking/index.tsx
> fix: add padding for legal disclaimer on mobile

- src/components/TokenLocking/BoostBreakdown.tsx
- adds 16px gap to boost breakdown current boost
Before:
After:
> fix: add gap to current boost

- pages/_app.tsx
- src/components/EnsureWalletConnection/index.tsx
- src/components/PageLayout/index.tsx
- src/hooks/useWeb3.ts
- When in a Safe App we do not disconnect the wallet by setting web3 to undefined
- Hide navigation in Splash Screen
> fix: hide navigation on splash screen, do not disconnect safe-apps

- src/components/SplashScreen/index.tsx
If the connected wallet is not a Safe, show a simple browser alert prompting to connect to a Safe Account.
> Fix: show an alert if not a Safe

- src/components/TokenLocking/BoostGraph/BoostGraph.tsx
- src/config/constants.ts
- src/utils/__tests__/boost.test.ts
- src/utils/boost.ts
- Extends early period by 6 days and adjusts time function accordingly
- Moves today label to the bottom to avoid overlaps
> feat: extend early period by 6 days

- src/hooks/useLeaderboard.ts
If no wallet is connected we no longer try to fetch the own rank for the campaign leaderboard.
> fix: do not fetch leaderboard if no wallet connected

- src/components/Points/ActivityPointsFeed.tsx
- src/components/Points/CampaignTabs.tsx
- src/components/Points/TotalPoints.tsx
- src/components/Points/index.tsx
- src/components/Points/styles.module.css
- src/components/TokenLocking/ActivityRewardsInfo.tsx
- src/hooks/useLatestCampaignUpdate.ts
- Show  last update separately from total points
- Fetch last weeks data
- show last weeks data in activity feed
- Show the total global points on the top right
- Redesign components
- Tab navigation
- Activity feed
> feat: show weekly update separately, redesign some components

- src/components/Points/ActivityPointsFeed.tsx
- Shows the latest update of the campaign separately
- Rephrases "last drop" to "Your last drop" as it reflects the last drop the Safe was a part of.
> fix: show latest campaign update

- src/analytics/navigation.ts
- src/components/ExternalLink/index.tsx
- src/components/Points/CampaignTabs.tsx
- src/components/Points/index.tsx
- src/components/TokenLocking/LockTokenWidget.tsx
- src/components/TokenLocking/index.tsx
- src/utils/analytics.ts
Adds new events for tracking campaigns and external links:
- `ExternalLink` will always track and add the `href` as `label`
- Tracking for `CampaignTab` navigation
> Analytics: campaign events
